# ==============================================================================
# Dockerfile
# Description: Containerizes the FastAPI prediction server + MLflow model.
#              Multi-stage friendly, minimal image.
# ==============================================================================

# ── Base image: slim Python 3.10 ──────────────────────────────────────────────
FROM python:3.10-slim

# ── Metadata ──────────────────────────────────────────────────────────────────
LABEL maintainer="fastapi_Docker"
LABEL description="Iris Classifier — MLflow + FastAPI packaged with Docker"

# ── Set working directory ─────────────────────────────────────────────────────
WORKDIR /app

# ── Copy dependency file first (leverages Docker layer cache) ─────────────────
COPY requirements.txt .

# ── Install Python dependencies ───────────────────────────────────────────────
RUN pip install --no-cache-dir -r requirements.txt

# ── Copy application code ─────────────────────────────────────────────────────
COPY app.py        .
COPY train.py      .

# ── Copy MLflow artifacts (model + mlruns folder) ────────────────────────────
# These are generated by running train.py before building the image
COPY mlruns/       ./mlruns/
COPY run_id.txt    .

# ── Expose FastAPI port ───────────────────────────────────────────────────────
EXPOSE 8000

# ── Environment variables ─────────────────────────────────────────────────────
ENV MLFLOW_TRACKING_URI=mlruns
ENV PYTHONUNBUFFERED=1

# ── Start the FastAPI server ──────────────────────────────────────────────────
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
